### ISSUE TITLE
Android5.0错误

### ISSUE THREAD

**Issue by satng** [wyouflf/xUtils#166]
04-06 14:35:04.669: E/AndroidRuntime(7864): FATAL EXCEPTION: main
04-06 14:35:04.669: E/AndroidRuntime(7864): Process: com.wetrip.app, PID: 7864
04-06 14:35:04.669: E/AndroidRuntime(7864): java.lang.StackOverflowError: stack size 8MB
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:04.669: E/AndroidRuntime(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(K
04-06 14:35:05.040: I/art(7864): Background partial concurrent mark sweep GC freed 96180(7MB) AllocSpace objects, 5(82MB) LOS objects, 15% free, 87MB/103MB, paused 1.220ms total 163.055ms
04-06 14:35:05.290: I/art(7864): Background partial concurrent mark sweep GC freed 87180(6MB) AllocSpace objects, 2(15MB) LOS objects, 12% free, 107MB/123MB, paused 1.251ms total 123.168ms
04-06 14:35:05.710: D/Error(7864): ERR: exClass=java.lang.StackOverflowError
04-06 14:35:05.710: D/Error(7864): ERR: exMsg=stack size 8MB
04-06 14:35:05.710: D/Error(7864): ERR: file=KeyExpiryMap.java
04-06 14:35:05.710: D/Error(7864): ERR: class=com.lidroid.xutils.util.core.KeyExpiryMap
04-06 14:35:05.710: D/Error(7864): ERR: method=get line=1
04-06 14:35:05.911: D/Error(7864): ERR: stack=java.lang.StackOverflowError: stack size 8MB
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:1)
04-06 14:35:05.911: D/Error(7864): 	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.containsKey(KeyExpiryMap.java:70)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.KeyExpiryMap.get(KeyExpiryMap.java:52)
04-06 14:35:05.911: D/Error(7864): 	at com.lidroid.xutils.util.core.K
04-06 14:35:05.931: D/Error(7864): ERR: TOTAL BYTES WRITTEN: 22865460
04-06 14:35:05.931: E/JavaBinder(7864): !!! FAILED BINDER TRANSACTION !!!

**Comment by satng** [comment]
更新到最版版可以解决，谁能告诉我为什么会这样，怎么样单个修复这个ＢＵＧ？

**Comment by huhuang03** [comment]
好像以前也碰到过这个问题，升级到最新版本久解决了，无法单独修复这个bug吧。你为什么不升级到最新版本呢

**Comment by LiuJunb** [comment]
单独的解决只能把内存缓存设计为false ：bitmapUtils.configDiskCacheEnabled(true);
		bitmapUtils.configMemoryCacheEnabled(false);
