### ISSUE TITLE
FATAL EXCEPTION com.lidroid.xutils.http.HttpHandler.onProgressUpdate

### ISSUE THREAD

**Issue by YLBFDEV** [wyouflf/xUtils#176]
06-01 10:26:41.995: E/AndroidRuntime(11805): FATAL EXCEPTION: main
06-01 10:26:41.995: E/AndroidRuntime(11805): Process: com.pztbiz.business, PID: 11805
06-01 10:26:41.995: E/AndroidRuntime(11805): java.lang.NullPointerException
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at com.xxx.xxxActivity$3.getIOAuthCallBack(xxx.java:131)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at com.xxx.xUtilsGet$1.onSuccess(xUtilsGet.java:55)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at com.lidroid.xutils.http.HttpHandler.onProgressUpdate(HttpHandler.java:218)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at com.lidroid.xutils.task.PriorityAsyncTask$InternalHandler.handleMessage(PriorityAsyncTask.java:385)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at android.os.Looper.loop(Looper.java:136)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
06-01 10:26:41.995: E/AndroidRuntime(11805): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Kerwin92** [comment]
I have the same error too.Anyone can give me some suggestions?
