### ISSUE TITLE
DbUtils查询数据时出现这个问题：access to method denied

### ISSUE THREAD

**Issue by sfsheng0322** [wyouflf/xUtils#210]
Column.setValue2Entity(L:65)﹕ access to method denied
java.lang.IllegalAccessException: access to method denied
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.lidroid.xutils.db.table.Column.setValue2Entity(Column.java:63)

**Comment by killpigman** [comment]
我也被这个问题困扰，只要findall，就会出现。
    java.lang.IllegalAccessException: access to method denied
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.lidroid.xutils.db.table.Column.setValue2Entity(Column.java:63)
            at com.lidroid.xutils.db.sqlite.CursorUtils.getEntity(CursorUtils.java:54)
            at com.lidroid.xutils.DbUtils.findAll(DbUtils.java:470)
            at com.lidroid.xutils.DbUtils.findAll(DbUtils.java:484)
请问您解决了吗？

**Comment by sfsheng0322** [comment]
没有啊
我觉得在Method.invoke之前没有调用setAccessable(true);
可以加上这个重新编译下库
