### ISSUE TITLE
打开数据库时出现 Failed to change locale for db '/data/data/xxxx/databases/faildPingBack' to 'zh_CN'.

### ISSUE THREAD

**Issue by waylife** [wyouflf/xUtils#211]
Failed to change locale for db '/data/data/xxxx/databases/faildPingBack' to 'zh_CN'.
``` java
8---android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/xxxx/databases/faildPingBack' to 'zh_CN'.

	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:397)

	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)

	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)

	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)

	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)

	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)

	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:829)

	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:814)

	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)

	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1076)

	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1065)

	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:250)

	at com.lidroid.xutils.DbUtils.<init>(SourceFile:57)

	at com.lidroid.xutils.DbUtils.getInstance(SourceFile:65)

	at com.lidroid.xutils.DbUtils.create(SourceFile:102)

	at xxxx.M.for(SourceFile:41)

	at xxxx..<init>(SourceFile:68)

	at xxxx..run(SourceFile:54)

	at android.os.Handler.handleCallback(Handler.java:808)

	at android.os.Handler.dispatchMessage(Handler.java:103)

	at android.os.Looper.loop(Looper.java:193)

	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by waylife** [comment]
参考链接http://stackoverflow.com/questions/19491675/failed-to-change-locale-for-db-data-data-my-easymedi-controller-databases-easy

**Comment by Guoxuelong** [comment]
你好，请问这个问题如何解决的啊？
