### ISSUE TITLE
https 不能支持tls1.2

### ISSUE THREAD

**Issue by cekowu** [wyouflf/xUtils#239]
HttpUrlConnection 如何支持https 协议tls1.2;
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): Connection closed by peer
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): javax.net.ssl.SSLException: Connection closed by peer
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.Connection.connect(Connection.java:107)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:223)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.loader.StringLoader.load(StringLoader.java:1)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:275)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-28 18:28:56.044: D/x_log:TaskProxy$InternalHandler.handleMessage(L:204)(17945): 	at java.lang.Thread.run(Thread.java:841)

**Comment by cekowu** [comment]
这个是报错的

**Comment by tymin** [comment]
请问 这个是报错，还是真不支持tls1.2

**Comment by cekowu** [comment]
xutil3 不支持tls1.2，要支持需要在RequestParams 设置自定义sslFactory;

private void setSSLFactory(RequestParams params){
    try {
         if(BaseApplication.getBaseInstance().isOnlySupportTls()){
            TlsOnlySocketFactory factory=new TlsOnlySocketFactory();
             params.setSslSocketFactory(factory);
         }
   
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
    }

**Comment by tymin** [comment]
谢谢回复，这样子，请问你访问的服务器是仅支持tls1.2 不向下兼容才会这样么？在请问一下，如果是xutils2.6.14呢？

**Comment by cekowu** [comment]
协议仅支持tls1.2， ssl 以及tls1.1 都有安全漏洞，所以服务器禁止了ssl 和tls协议的访问

**Comment by cekowu** [comment]
xutils2.6.14  http client 添加自定义factory更简单

**Comment by tymin** [comment]
十分感谢，2.6.14 那如果我不设置自定义的factory，访问tls1.2的是不是就会访问失败，

**Comment by cekowu** [comment]
肯定的

**Comment by tymin** [comment]
明白了。麻烦了

**Comment by tymin** [comment]
好的，麻烦了，可以提供一下服务器地址么？我们这边也想变成只支持tls1.2但是没有网站可以测试，所以希望借助你的资源可以么？谢谢了

**Comment by cekowu** [comment]
不好意思，我们内部测试地址，无法开放到外部

**Comment by tymin** [comment]
好的，谢谢你
